### ISSUE TITLE
有关chybeta网页的问题

### ISSUE THREAD

**Issue by 687766616e** [CHYbeta/cmsPoc#3]
https://chybeta.github.io/2017/10/15/DiscuzX-v3-4-%E4%BB%BB%E6%84%8F%E6%96%87%E4%BB%B6%E5%88%A0%E9%99%A4%E6%BC%8F%E6%B4%9E/

文章写道`discuzx` 但是不对的 ^^'' 应该是`discuz`

> 登陆后获取cookie后，命令行：
> 
> python cmspoc.py -u http://10.10.10.1:2500/DiscuzX/upload/home.php -t discuzx -s v34_delete_arbitrary_files

**Comment by huitc** [comment]
然後.........
